### ISSUE TITLE
credentials was not accepted

### ISSUE THREAD

**Issue by Abdelhalim38** [mehdichaouch/YAWAC#3]
Salut
J'ai toujours le message "credentials was not accepted" dans le log et pas de conexion 
Les identifiants vérifier
Avec le command "yawac.sh --freewifi mylogin mypassword" ça marche mais pas automatiquement 
Merci d'avance

**Comment by mehdichaouch** [comment]
Ce script a été crée il y a deux ans, il se peut qu'il ne fonctionne plus avec les nouvelles pages de connexion de FreeWifi.
Si je trouve le temps, je ferai un test.

**Comment by Abdelhalim38** [comment]
Merci frère

**Comment by Abdelhalim38** [comment]
Bonjour
Il y a des nouvelles sur ce script?
Connaissez vous une alternative pour auto loging de FreeWifi desde openwrt
Merci

**Comment by mehdichaouch** [comment]
Bonjour,
Pas de nouveauté sur ce script et je ne suis plus en mesure de pouvoir le faire évoluer actuellement pour des raisons techniques.
